### ISSUE TITLE
licenses fix

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#52]
You have to normalize all the strange licenses strings from upstream and use ` ` as separator not `,`

**Comment by allenh1** [comment]
Could you please clarify what you mean by "Normalize"? I currently just pull the license listed by the ROS package maintainers (the one(s) found in the `package.xml` file).

But, honestly, my first priority is making sure that `desktop_full` emerges successfully. Have you been able to do this yet?

**Comment by Alessandro-Barbieri** [comment]
For example:
`LICENSE="Apache License 2.0"` -> `LICENSE="Apache-2.0"`
`LICENSE="Apache"` -> find the exact version
`LICENSE="Apache 2.0"` -> `LICENSE="Apache-2.0"`
`LICENSE="Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)"` -> `LICENSE="Apache-2.0"`
`LICENSE="BSD,LGPL,Apache 2.0` -> `LICENSE="BSD LGPL-<version> Apache-2.0`

No because I have to accept all the shitty strings as licenses

**Comment by allenh1** [comment]
> No because I have to accept all the shitty strings as licenses

Do you mean you personally, or is this a thing you have to configure in portage? Because I've not seen portage complain about it yet.

I don't mean to say this is not important, as it definitely is. I just want to make sure the ebuilds work before I work on perfecting the small details. By the end of this, I really want these ebulds to be super solid, and I really do appreciate all the feedback you're giving me. This kind of feedback is how adequate software becomes great software, so thank you for paying such close attention to this project.

**Comment by Alessandro-Barbieri** [comment]
Depends on what your `ACCEPT_LICENSE` contains.
Mine is `ACCEPT_LICENSE="-* @FREE VOSTROM"` while default I think is ACCEPT_LICENSE="* -@EULA"

I'll temporary change my `ACCEPT_LICENSE` and try

**Comment by allenh1** [comment]
Thank you very much!

**Comment by Alessandro-Barbieri** [comment]
I'm having dependency failures

**Comment by allenh1** [comment]
Could you file an issue with the relevant part of the emerge output for me please?

**Comment by Alessandro-Barbieri** [comment]
Them are not from this overlay nor ros-related

**Comment by allenh1** [comment]
Ok, cool.

**Comment by allenh1** [comment]
@Alessandro-Barbieri What's the status of this? Do you have any other license tests that should be tested?

The above are being added to superflore via ros-infrastructure/superflore#73.

**Comment by Alessandro-Barbieri** [comment]
Let's close for now since travis is not working
